orderitem_index:
    path:     /
    defaults: { _controller: "NubbeBundle:OrderItem:index" }
    methods:  GET

orderitem_show:
    path:     /{id}/show
    defaults: { _controller: "NubbeBundle:OrderItem:show" }
    methods:  GET

orderitem_new:
    path:     /new
    defaults: { _controller: "NubbeBundle:OrderItem:new" }
    methods:  [GET, POST]

orderitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "NubbeBundle:OrderItem:edit" }
    methods:  [GET, POST]

orderitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "NubbeBundle:OrderItem:delete" }
    methods:  DELETE
