nubbe_productlist:
    path:     /productList/{category}
    defaults: { _controller: NubbeBundle:Default:productlist }

nubbe_productlist_new:
    path:     /productListNew
    defaults: { _controller: NubbeBundle:Default:productlistNew }

nubbe_productdetail:
    path:     /productdetail/{product}/{colorId}
    defaults: { _controller: NubbeBundle:Default:productdetail }