nubbe_homepage:
    path:     /
    defaults: { _controller: NubbeBundle:Default:index }

nubbe_contact:
    path:     /contact
    defaults: { _controller: NubbeBundle:Default:contact }

nubbe_quiensomos:
    path:     /quiensomos
    defaults: { _controller: NubbeBundle:Default:quiensomos }
