NubbeBundle\Entity\OrderItem:
    type: entity
    table: null
    repositoryClass: NubbeBundle\Repository\OrderItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
        productId:
            type: integer
        colorId:
            type: integer
        colorName:
            type: string
            length: 255
        foto:
            type: string
            length: 255
    manyToOne:
        orderInfo:
            targetEntity: OrderInfo
            inversedBy: orderItems
            joinColumn:
                name: orderInfo_id
                referencedColumnName: id
        product:
            targetEntity: Product
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
